# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cjules < Formula
  desc "Power-user cli for the jules api, written in crystal"
  homepage "https://github.com/hahwul/cjules"
  url "https://github.com/hahwul/cjules/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "20bcc66313b8fc11ea26c8511be8aff761803a2ce029b6acce0208bb4fa1c663"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/cjules"
  end

  test do
    system "#{bin}/cjules", "version"
  end
end
