# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cjules < Formula
  desc "Power-user cli for the jules api, written in crystal"
  homepage "https://github.com/hahwul/cjules"
  url "https://github.com/hahwul/cjules/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "02ccf4be6075396681378180c8255f7038f2e5201ced3c248f7e4b30f3ffae07"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/cjules"
  end

  test do
    system "#{bin}/cjules", "version"
  end
end
