# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cjules < Formula
  desc "Power-user cli for the jules api, written in crystal"
  homepage "https://github.com/hahwul/cjules"
  url "https://github.com/hahwul/cjules/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "52489f12d49e79f012731732e8fab8fb5455fd1e82e292d885f2bfc6256de3d6"
  license "MIT"

  depends_on "crystal"

  def install
    system "shards install"
    system "shards build --release --no-debug --production"
    bin.install "bin/cjules"
  end

  test do
    system "#{bin}/cjules", "version"
  end
end
